name: Run Q-Learning Comparison

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install reportlab

      - name: Run Baseline (무학습 대조군)
        run: |
          python src/compare_baseline.py

      - name: Run Q-Learning (학습군)
        run: |
          python src/train.py

      - name: Visualize Results
        run: |
          python src/visualize.py

      - name: Make PDF Report (한국어 비교 리포트)
        run: |
          python src/make_report.py

      - name: Upload all results
        uses: actions/upload-artifact@v4
        with:
          name: q-learning-comparison-results
          path: results
