# .github/workflows/run-training.yml
name: Run Q-Learning Training

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: |
          python src/train.py --episodes 2000 || python src/train.py

      - name: Visualize policy
        run: |
          python src/visualize.py || echo "visualize failed"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: q-learning-results
          path: results
